package helpinghands.allocation.service.impl;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import helpinghands.allocation.dto.AllocatedItemDTO;
import helpinghands.allocation.dto.AllocationResponseDTO;
import helpinghands.allocation.dto.AllocationUpdateDTO;
import helpinghands.allocation.entity.AllocatedFoodItem;
import helpinghands.allocation.entity.Allocation;
import helpinghands.allocation.repository.AllocationRepository;
import helpinghands.allocation.service.AllocationService;
import helpinghands.beneficiary.entity.Beneficiary;
import helpinghands.beneficiary.repository.BeneficiaryRepository;
import helpinghands.inventory.entity.DonationItem;
import helpinghands.inventory.repository.FoodRepository;
import helpinghands.request.entity.Request;
import helpinghands.request.repository.RequestRepository;
import helpinghands.util.EntityManager;
import helpinghands.util.EntityManager.DTOKey;
import helpinghands.util.MessageConstants.ErrorMessages;
import helpinghands.util.exceptions.InvalidAllocationException;

/**
 * 
 *
 * @version 1.0
 *
 */
@Service
public class AllocationServiceImpl implements AllocationService {

	/**
	 * Dependency injection
	 */
	@Autowired
	private AllocationRepository allocationRepository;
	
	/**
	 * Dependency injection
	 */
	@Autowired
	private RequestRepository requestRepository;
	
	/**
	 * Dependency injection
	 */
	@Autowired
	private BeneficiaryRepository beneficiaryRepository;
	
	/**
	 * Dependency injection
	 */
	@Autowired
	private FoodRepository foodRepository;
	
	/**
	 * Retrieves all the allocations that have been generated by the system
	 */
	@Override
	public List<AllocationResponseDTO> retrieveAllAllocations() {
		// TODO Auto-generated method stub
		List<Allocation> allocations = allocationRepository.findAll();
		List<AllocationResponseDTO> response = new ArrayList<AllocationResponseDTO>();
		for(Allocation allocation : allocations) {
			response.add((AllocationResponseDTO)EntityManager.convertToDTO(DTOKey.AllocationResponseDTO, allocation));
		}
		return response;
	}
	
	/**
	 * Retrieves all the allocated food items for the specified beneficiary, wrapped in a DTO for the client viewing
	 */
	@Override
	public List<AllocatedItemDTO> retrieveAllocationByBeneficiary(String beneficiary) {
		// TODO Auto-generated method stub
		Allocation allocation = allocationRepository.findByBeneficiaryUserUsername(beneficiary);
		List<AllocatedFoodItem> allocatedItems = allocation.getAllocatedItems();
		return EntityManager.convertAllocatedFoodItemListToDTOList(allocatedItems);
	}

	/**
	 * Generates the allocation with the algorithm in-built to the system
	 */
	@Override
	public void generateAllocationList() {
		// TODO Auto-generated method stub
		List<Request> requests = requestRepository.findAll();
		List<Beneficiary> beneficiaries = beneficiaryRepository.findAll();
		Map<String, Double> beneficiariesScoreTable = generateBeneficiaryScoreTable(beneficiaries);
		Map<String, Allocation> allocationMap = generateAllocationMapping(generateMapping(requests), beneficiariesScoreTable);
		allocationRepository.saveAll(allocationMap.values());
	}
	
	/**
	 * Generate a temporary beneficiary score table used in the allocation process
	 * @param beneficiaries
	 * @return Map<String, Double> with the key: beneficiary username, value: score
	 */
	private Map<String, Double> generateBeneficiaryScoreTable(List<Beneficiary> beneficiaries) {
		Map<String, Double> beneficiariesScoreTable = new HashMap<String, Double>();
		for(Beneficiary beneficiary : beneficiaries) {
			beneficiariesScoreTable.put(beneficiary.getUser().getUsername(), beneficiary.getScore());
		}
		return beneficiariesScoreTable;
	}

	/**
	 * Generate a HashMap that details all the requests made for a certain food item
	 * @param requests
	 * @return HashMap that stores a List<Request> made for a certain food item
	 */
	private HashMap<String, List<Request>> generateMapping(List<Request> requests) {
		HashMap<String, List<Request>> requestsByFoodItems = new HashMap<String, List<Request>>();
		for(Request request : requests) {
			String category = request.getFoodItem().getCategory();
			String classification = request.getFoodItem().getClassification();
			String description = request.getFoodItem().getDescription();
			String key = category + "," + classification + "," + description;
			List<Request> requestsContainingFoodItem = requestsByFoodItems.get(key);
			if(requestsContainingFoodItem != null) {
				requestsContainingFoodItem.add(request);
				requestsByFoodItems.replace(key, requestsContainingFoodItem);
			} else {
				requestsContainingFoodItem = new ArrayList<Request>();
				requestsContainingFoodItem.add(request);
				requestsByFoodItems.put(key, requestsContainingFoodItem);
			}
		}
		return requestsByFoodItems;
	}
	
	/**
	 * Generate a Map that details the Allocations for each beneficiary
	 * @param requestsByFoodItems
	 * @param beneficiariesScoreTable
	 * @return Map<String, Allocation> which details the Allocation that each beneficiary is receiving
	 */
	private Map<String, Allocation> generateAllocationMapping(Map<String, List<Request>> requestsByFoodItems, Map<String, Double> beneficiariesScoreTable) {
		// The key for this map will be the username of the beneficiaries
		// The value for this map will be allocation object of each beneficiary
		Map<String, Allocation> allocationMap = new HashMap<String, Allocation>();
		List<DonationItem> foodItemsAllocated = new ArrayList<DonationItem>();
		List<Request> zeroAllocatedRequests = new ArrayList<Request>();
		for(Map.Entry<String, List<Request>> entry : requestsByFoodItems.entrySet()) {
			// If the value of the entry is non-null, we know that this item has been requested by some beneficiaries
			List<Request> requestsForFoodItem = entry.getValue();
			// Retrieving only the first request because all the requests within the list are referencing the same item
			Request request = requestsForFoodItem.size() > 0 ? requestsForFoodItem.get(0) : null;
			if(request != null) {
				DonationItem dbFoodItem = request.getFoodItem();
				Integer inventoryQuantity = dbFoodItem.getQuantity();
				foodItemsAllocated.add(dbFoodItem);
				Integer numberOfBeneficiariesAllocated = requestsForFoodItem.size();
				Double totalScore = Double.valueOf(0);
				numberOfBeneficiariesAllocated = evaluateOptimalBeneficiaryAllocationCount(numberOfBeneficiariesAllocated, inventoryQuantity);
				for(int i = 0; i < numberOfBeneficiariesAllocated; i++) {
					totalScore += requestsForFoodItem.get(i).getBeneficiary().getScore();
				}
				// Sorting the requests to prioritize based on the beneficiary's existing ranking in the score table
				requestsForFoodItem.sort((Request r1, Request r2)->(int)(beneficiariesScoreTable.get(r1.getBeneficiary().getUser().getUsername()) - beneficiariesScoreTable.get(r2.getBeneficiary().getUser().getUsername())));
				// Reversing the Collection to ensure the highest scorer is in the first position, and so-forth
				Collections.reverse(requestsForFoodItem);
				LinkedHashMap<String, AllocatedFoodItem> unfulfilledRequests = new LinkedHashMap<>();
				for(int i = 0; i < requestsForFoodItem.size(); i++) {
					Request currentRequest = requestsForFoodItem.get(i);
					beneficiariesScoreTable.get(currentRequest.getBeneficiary().getUser().getUsername());
					Double beneficiaryScore = currentRequest.getBeneficiary().getScore();
					Double allocationRatio = beneficiaryScore/totalScore;
					Integer maxAllocatedQuantity = (int)Math.ceil(allocationRatio * inventoryQuantity);
					Integer allocatedQuantity = Integer.valueOf(0);
					Integer requestedQuantity = currentRequest.getRequestedQuantity();
					// Inventory quantity will not fall below 0
					// If inventory quantity reaches 0, all beneficiaries will be allocated 0 for the item
					if(inventoryQuantity > 0) {
						// When inventory is sufficient to allocate to this beneficiary
						if(maxAllocatedQuantity <= inventoryQuantity) {
							// Conditional for when beneficiary request for more than what they can get
							// Written using a ternary operator
							allocatedQuantity = requestedQuantity > maxAllocatedQuantity ? maxAllocatedQuantity : requestedQuantity;
						} else {
							// Enter this block if inventory is insufficient to meet maxAllocatedQuantity
							maxAllocatedQuantity = inventoryQuantity;
							allocatedQuantity = requestedQuantity > maxAllocatedQuantity ? maxAllocatedQuantity : requestedQuantity;
						}
					}
					inventoryQuantity -= allocatedQuantity;
					String beneficiaryUsername = currentRequest.getBeneficiary().getUser().getUsername();
					Allocation allocation = allocationMap.get(beneficiaryUsername);
					DonationItem foodItem = currentRequest.getFoodItem();
					// Modifying the score of each beneficiary after allocation of this food item
					Double oldScore = beneficiariesScoreTable.get(beneficiaryUsername);
					beneficiariesScoreTable.put(beneficiaryUsername, (double)(oldScore - allocatedQuantity));
					AllocatedFoodItem allocationByAlgorithm = new AllocatedFoodItem(foodItem, requestedQuantity, allocatedQuantity);
					// Check if the beneficiary already has other allocated food items
					if(allocation != null) {
						allocationByAlgorithm.setAllocation(allocation);
						allocation.getAllocatedItems().add(allocationByAlgorithm);
						allocationMap.replace(beneficiaryUsername, allocation);
					} else {
						// This block will only be entered if the beneficiary currently has no other allocation of food items
						ArrayList<AllocatedFoodItem> foodItems = new ArrayList<AllocatedFoodItem>();
						foodItems.add(allocationByAlgorithm);
						allocation = new Allocation(currentRequest.getBeneficiary(), foodItems, Boolean.FALSE);
						for(AllocatedFoodItem allocationListItem : foodItems) {
							allocationListItem.setAllocation(allocation);
						}
						allocationMap.put(beneficiaryUsername, allocation);
					}
					if(requestedQuantity > allocatedQuantity) {
						// Unfulfilled requests mapping
						unfulfilledRequests.put(beneficiaryUsername, allocationByAlgorithm);
						if(allocatedQuantity == 0) {
							zeroAllocatedRequests.add(currentRequest);
						}
					}
				}
				allocateLeftovers(unfulfilledRequests, allocationMap, inventoryQuantity);
			}
			allocateSimilarFoodItems(allocationMap, foodItemsAllocated, zeroAllocatedRequests);
		}
		return allocationMap;
	}
	
	private void allocateSimilarFoodItems(Map<String, Allocation> allocationMap, List<DonationItem> foodItemsAllocated,
			List<Request> zeroAllocatedRequests) {
		// TODO Auto-generated method stub
		List<DonationItem> allFoodItems = foodRepository.findAll();
		Iterator<Request> zeroAllocatedRequestIterator = zeroAllocatedRequests.iterator();
		while(zeroAllocatedRequestIterator.hasNext()) {
			Request unfulfilledRequest = zeroAllocatedRequestIterator.next();
			// Look for similar items across all items that have not been affected by the initial allocation
			DonationItem requestFoodItem = unfulfilledRequest.getFoodItem();
			int unfulfilledRequestQuantity = unfulfilledRequest.getRequestedQuantity();
			String beneficiaryUsername = unfulfilledRequest.getBeneficiary().getUser().getUsername();
			int allocatedQuantity = 0;
			for(DonationItem dbFoodItem : allFoodItems) {
				if(!foodItemsAllocated.contains(dbFoodItem) && dbFoodItem.getQuantity() > 0) {
					String dbFoodItemCategory = dbFoodItem.getCategory();
					String dbFoodItemClassification = dbFoodItem.getClassification();
					String[] dbFoodItemDescription = dbFoodItem.getDescription().split("-");
					int dbFoodItemQuantity = dbFoodItem.getQuantity();
					if(dbFoodItemQuantity == 0) {
						break;
					}
					String requestCategory = requestFoodItem.getCategory();
					String requestClassification = requestFoodItem.getClassification();
					String[] requestDescription = requestFoodItem.getDescription().split("-");
					if(requestCategory.equals(dbFoodItemCategory) && requestClassification.equals(dbFoodItemClassification)) {
						// Halal products will have an array of size 2, while non-Halal products will have an array of size 1
						if(requestDescription.length == dbFoodItemDescription.length) {
							if(requestDescription[0].equals(dbFoodItemDescription[0])) {
								// This block will only be entered if the food item name is similar, but of different weight
								double dbFoodItemWeight = normalizeWeight(dbFoodItemDescription);
								double requestFoodItemWeight = normalizeWeight(requestDescription);
								double requestTotalWeight = requestFoodItemWeight * unfulfilledRequestQuantity;
								double dbTotalWeight = dbFoodItemWeight *  dbFoodItemQuantity;
								if(dbTotalWeight >= requestTotalWeight) {
									// This block will only be entered if the selected item within the DB has a total weight that is larger than the request total weight
									allocatedQuantity = (int)(requestTotalWeight / dbFoodItemWeight);
									dbFoodItemQuantity = dbFoodItemQuantity - allocatedQuantity;
									Allocation allocation = allocationMap.get(beneficiaryUsername);
									System.out.println("Retrieving allocation from map for the beneficiary = " + beneficiaryUsername);
									// Requested Quantity is set to 0 because the beneficiary technically did not request for this item, but was assigned it due to the similarity score
									AllocatedFoodItem allocatedBySimilarity = new AllocatedFoodItem(dbFoodItem, 0, allocatedQuantity);
									allocatedBySimilarity.setAllocation(allocation);
									allocation.getAllocatedItems().add(allocatedBySimilarity);
									allocationMap.replace(beneficiaryUsername, allocation);
									break;
									/*
									if(dbTotalWeight >= requestTotalWeight) {
										break;
									}
									*/
								} else {
									// This block will only be entered if the selected item within the DB has a total weight that is less than the request total weight
									allocatedQuantity = dbFoodItemQuantity;
									// This is to force the next loop to break
									dbFoodItemQuantity = 0;
									Allocation allocation = allocationMap.get(beneficiaryUsername);
									System.out.println("xxxxxxxxxxxxxxxxxx ELSE : " + beneficiaryUsername);
									AllocatedFoodItem allocatedBySimilarity = new AllocatedFoodItem(dbFoodItem, 0, allocatedQuantity);	//0 represents the requested quantity which is 0
									allocatedBySimilarity.setAllocation(allocation);
									allocation.getAllocatedItems().add(allocatedBySimilarity);
									allocationMap.replace(beneficiaryUsername, allocation);
									break;
								}
							}
						}
					}
				}
			}
			zeroAllocatedRequestIterator.remove();
		}
	}

	private double normalizeWeight(String[] description) {
		// TODO Auto-generated method stub
		String weightInString = description[1];
		Double weight = Double.valueOf(0);
		if(weightInString.contains("kg")) {
			weightInString = weightInString.replace("kg", "");
			weight = Double.parseDouble(weightInString) * 1000;
		} else if (weightInString.contains("ml")) {
			weightInString = weightInString.replace("ml", "");
			weight = Double.parseDouble(weightInString);
		} else if (weightInString.contains("g")) {
			weightInString = weightInString.replace("g", "");
			weight = Double.parseDouble(weightInString);
		} else if (weightInString.contains("l")) {
			weightInString = weightInString.replace("l", "");
			weight = Double.parseDouble(weightInString) * 1000;
		}
		return weight;
	}

	private void allocateLeftovers(LinkedHashMap<String, AllocatedFoodItem> unfulfilledRequests, Map<String, Allocation> allocationMap, Integer inventoryQuantity) {
		if(!unfulfilledRequests.keySet().isEmpty()) {
			while(inventoryQuantity > 0) {
				if(unfulfilledRequests.keySet().isEmpty()) {
					break;
				}
				String usernameKey = unfulfilledRequests.keySet().iterator().next();
				AllocatedFoodItem unfulfilledRequest = unfulfilledRequests.get(usernameKey);
				unfulfilledRequests.remove(usernameKey);
				Integer allocatedQuantity = unfulfilledRequest.getAllocatedQuantity();
				Integer requestedQuantity = unfulfilledRequest.getRequestedQuantity();
				Integer difference = requestedQuantity - allocatedQuantity;
				if(difference >= inventoryQuantity) {
					unfulfilledRequest.setAllocatedQuantity(unfulfilledRequest.getAllocatedQuantity() + inventoryQuantity);
					inventoryQuantity -= inventoryQuantity;
					break;
				} else {
					unfulfilledRequest.setAllocatedQuantity(unfulfilledRequest.getAllocatedQuantity() + difference);
					inventoryQuantity -= difference;
				}
				DonationItem unfulfilledRequestFoodItem = unfulfilledRequest.getFoodItem();
				String category = unfulfilledRequestFoodItem.getCategory();
				String classification = unfulfilledRequestFoodItem.getClassification();
				String description = unfulfilledRequestFoodItem.getDescription();
				Allocation allocation = allocationMap.get(usernameKey);
				// Iterator is generated here to remove previously added AllocatedFoodItem
				Iterator<AllocatedFoodItem> allocationListIterator = allocation.getAllocatedItems().iterator();
				while(allocationListIterator.hasNext()) {
					AllocatedFoodItem allocatedFoodItem = allocationListIterator.next();
					DonationItem allocatedDbFoodItem = allocatedFoodItem.getFoodItem();
					if(allocatedDbFoodItem.getCategory().equals(category) && 
							allocatedDbFoodItem.getClassification().equals(classification) &&
							allocatedDbFoodItem.getDescription().equals(description)) {
						allocation.getAllocatedItems().add(unfulfilledRequest);
						unfulfilledRequest.setAllocation(allocation);
						allocationMap.replace(usernameKey, allocation);
						break;
					}
				}
			}
		}
	}
	
	private Integer evaluateOptimalBeneficiaryAllocationCount(Integer numberOfBeneficiariesAllocated, Integer inventoryQuantity) {
		Integer maxNumberBeneficiariesPerFoodItem = 0;
		if(inventoryQuantity < 50) {
			maxNumberBeneficiariesPerFoodItem = 5;
		} else if (inventoryQuantity < 100) {
			maxNumberBeneficiariesPerFoodItem = 10;
		} else {
			maxNumberBeneficiariesPerFoodItem = 20;
		}
		if(numberOfBeneficiariesAllocated > maxNumberBeneficiariesPerFoodItem) {
			numberOfBeneficiariesAllocated = maxNumberBeneficiariesPerFoodItem;
		} 
		return numberOfBeneficiariesAllocated;
	}
	
	@Override
	public void updateAllocation(AllocationUpdateDTO allocation) {
		// TODO Auto-generated method stub
		Allocation dbAllocation = allocationRepository.findByBeneficiaryUserUsername(allocation.getBeneficiary());// Id(allocation.getId());
		if(dbAllocation == null) {
			throw new InvalidAllocationException(ErrorMessages.INVALID_ALLOCATION);
		}
		List<AllocatedFoodItem> dbAllocatedItems = dbAllocation.getAllocatedItems();
		Map<String, Integer> dbAllocationMap = new HashMap<String, Integer>();
		for(int i = 0; i < dbAllocatedItems.size(); i++) {
			AllocatedFoodItem allocatedFoodItem = dbAllocatedItems.get(i);
			String key = allocatedFoodItem.getFoodItem().getCategory() + "," + 
					allocatedFoodItem.getFoodItem().getClassification() + "," + 
					allocatedFoodItem.getFoodItem().getDescription();
			dbAllocationMap.put(key, i);
		}
		List<Map<String, Object>> updatedAllocatedItems = allocation.getAllocatedItems();
		for(Map<String, Object> updatedAllocatedItemMap : updatedAllocatedItems) {
			String category = (String)updatedAllocatedItemMap.get("category");
			String classification = (String)updatedAllocatedItemMap.get("classification");
			String description = (String)updatedAllocatedItemMap.get("description");
			Integer allocatedQuantity = (Integer)updatedAllocatedItemMap.get("allocatedQuantity");
			String key = category + "," + classification + "," + description;
			dbAllocatedItems.get(dbAllocationMap.get(key)).setAllocatedQuantity(allocatedQuantity);
		}
		dbAllocation.setAllocatedItems(dbAllocatedItems);
		allocationRepository.save(dbAllocation);
	}

	@Override
	public void approveAllocations() {
		// TODO Auto-generated method stub
		List<Allocation> allocations = allocationRepository.findAll();
		for(Allocation allocation : allocations) {
			allocation.setApprovalStatus(true);
		}
		allocationRepository.saveAll(allocations);
	}

	@Override
	public Boolean checkApproveStatus() {
		// TODO Auto-generated method stub
		Boolean result = true;
		List<Allocation> allocations = allocationRepository.findAll();
		for(Allocation allocation : allocations) {
			if(!allocation.getApprovalStatus()) {
				result = false;
				break;
			}
		}
		return result;
	}

}
