package helpinghands.admin.dto;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * 
 *
 * @version 1.0
 *
 */
public class WindowDataDTO {
	
	/**
	 * A boolean value that represents the window status
	 * TRUE if the existing window is open, FALSE otherwise
	 */
	@NotNull
	@JsonProperty("windowStatus")
	private Boolean windowStatus;
	
	/**
	 * String value that represents the window start date
	 */
	@NotNull
	@JsonProperty("windowStartDate")
	private String startDate;
	
	/**
	 * String value that represents the window end date
	 */
	@NotNull
	@JsonProperty("windowEndDate")
	private String endDate;
	
	/**
	 * Double that represents the multiplier rate to be used
	 */
	@NotNull
	@JsonProperty("multiplierRate")
	private Double multiplierRate;
	
	/**
	 * Double that represents the decay rate to be used
	 */
	@NotNull
	@JsonProperty("decayRate")
	private Double decayRate;
	
	/**
	 * Daily password that will be generated by the system
	 */
	@NotNull
	@JsonProperty("dailyPassword")
	private String dailyPassword;
	
	/**
	 * Integer value that represents the number of unique beneficiaries who have made requests in the current window
	 */
	@NotNull
	@JsonProperty("uniqueBeneficiaryCount")
	private Integer uniqueBeneficiaryCount;

	/**
	 * Empty constructor that should not be initialized in most instances
	 * Required for Spring injection
	 */
	protected WindowDataDTO() {}
	
	/**
	 * Constructor that allows the initialization of the WindowData DTO
	 * @param windowStatus
	 * @param startDate
	 * @param endDate
	 * @param multiplierRate
	 * @param decayRate
	 * @param dailyPassword
	 * @param uniqueBeneficiaryCount
	 */
	public WindowDataDTO(Boolean windowStatus, String startDate, String endDate, Double multiplierRate,
			Double decayRate, String dailyPassword, Integer uniqueBeneficiaryCount) {
		this.windowStatus = windowStatus;
		this.startDate = startDate;
		this.endDate = endDate;
		this.multiplierRate = multiplierRate;
		this.decayRate = decayRate;
		this.dailyPassword = dailyPassword;
		this.uniqueBeneficiaryCount = uniqueBeneficiaryCount;
	}

}
